EXCHANGE_RATES_BASE_URL = "https://api.ratesapi.io/api/"

BNB_DATE_FORMAT = "%Y-%m-%d"

NAP_DIGIT_PRECISION = "0.01"
NAP_DATE_FORMAT = "%Y-%m-%d"
NAP_DIVIDEND_TAX = "0.05"

RECEIVED_DIVIDEND_ACTIVITY_TYPES = ["DIV", "DIVCGL", "DIVCGS", "DIVROC", "DIVTXEX"]
TAX_DIVIDEND_ACTIVITY_TYPES = ["DIVNRA", "DIVFT", "DIVTW"]